name: hello
on:
  workflow_call:
    inputs:
      with_runner:
        required: false
        description: Whether to use a runner
        default: false
        type: boolean

jobs:
  say_hello:
    runs-on: ${{ inputs.with_runner && 'ubuntu-latest' || 'self-hosted' }}
    steps:
      - uses: actions/checkout@v4
      - name: Say Hello
        run: echo "${{ inputs.with_runner && 'Hello WITH runner' || 'Hello WITHOUT runner' }}"