name: Main

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  print_source_branch_name:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: Get Source Branch name
        run: echo "Source Branch Name is - ${{ github.head_ref }}"